services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 12

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: rabbit-app
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RACE_EXCHANGE=race_events
      - PUBLISH_INTERVAL_SECONDS=2

  consumer1:
    build:
      context: .
      dockerfile: consumer/Dockerfile.consumer1
    container_name: rabbit-consumer1
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RACE_EXCHANGE=race_events
      - RABBITMQ_QUEUE_CONSUMER1=race_events_consumer1

  consumer2:
    build:
      context: .
      dockerfile: consumer/Dockerfile.consumer2
    container_name: rabbit-consumer2
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RACE_EXCHANGE=race_events
      - RABBITMQ_QUEUE_CONSUMER2=race_events_consumer2
