FROM mirror.gcr.io/library/python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /consumer

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer/consumer2.py .

CMD python3 consumer2.py
